"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import useMount from "@/hooks/useMount";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { mounted } = useMount();
  return (
    <html lang="en">
      <body className={inter.className}>{mounted ? children : <></>}</body>
    </html>
  );
}
